export {listCourseRouter} from './list'
export {createCourseRouter} from './new'
export {showCourseRouter} from './show'
export {updateCourseRouter} from './update'
export {deleteCourseRouter} from './delete'